#!/usr/bin/env bash
# installs nginx web server on a new ubuntu server and redirects
sudo apt update
sudo apt -y install nginx
sudo ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.html
echo "server {
	listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;
        index index.html;

        location /redirect_me {
                return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
        }
}" > default

sudo mv -f default /etc/nginx/sites-available/default
sudo service nginx restart
