#!/usr/bin/env bash
# Install and configure HAproxy on your load balancer

ufw allow 1344
apt-get -y update
apt-get install -y haproxy

printf %s "
backend nginx_backend
        balance roundrobin
        option forwardfor
        server 112955-web-01 54.236.49.194:80 check
        server 112955-web-02 52.91.125.113:80 check
frontend proxynode
        bind *:80
        mode http
        default_backend nginx_backend
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
