#!/usr/bin/env bash
# reconfigures nginx
# sudo rm /etc/nginx/sites-enabled/default
# sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
# sudo service nginx start
sudo apt update
sudo apt install nginx
sudo service nginx start
