#!/usr/bin/env bash
# creates a files that containing its PID
# displays to infinity and beyond indefinitely
# displays I hate the kill command when receiving SIGTERM
# displays Y u no love when it receives SIGINT
# deletes when SIGQUIT AND SIGTERM are entered

echo "$$" > /var/run/myscript.pid

func_del()
{
	rm /var/run/myscript.pid
	exit
}

while true
do
 echo "To infinity and beyond"
 sleep 2
 trap 'echo "Y U no love me?!"' SIGINT
 trap 'echo "I hate the kill command" && func_del' SIGTERM
 trap 'func_del' SIGQUIT
done
