#!/usr/bin/env bash
# Displays : to infinity and beyond indefinitely
# sleep 2
# I am invincible when it receives a SIGTERM signal

while true
do
 echo "To infinity and beyond"
 sleep 2
 trap 'echo "I am invincible!!!"' SIGTERM
done
