#!/usr/bin/env bash
# displays numbers from 1 to 100
# display fizzbuzz when number is multiple of 3 and 5
# display fizz when the number is multiple of 3
# display buzz when the number is multiple of 5
#  otherwise display the number in list format

for i in {1..100}
do
 if (( i % 3 == 0 && i % 5 == 0 ))
 then
  echo "fizzbuzz"
 elif (( i % 3 == 0 ))
 then
  echo "fizz"
 elif (( i % 5 == 0 ))
 then
  echo "buzz"
 else
  echo "$i"
 fi
done
