#!/usr/bin/env bash
# loops from 1 to 10 and at 4th display bad luck and 8th good luck
  and best school

i=0
while [ $i -lt 10 ]
do
 if [ $i -eq 3 ]
 then
  echo "bad luck"
 elif [ $i -eq 7 ]
 then
  echo "good luck"
 else
  echo "Best School"
 fi
  (( i++))
done
