#!/usr/bin/env bash
# displays numbers from 1 to 20 and:
#  at 4 display badluck from china
#  at 9 display badluck from Japan
#  at 17 display badluck from Italy

i=1

while [ $i -le 20 ]
do
  echo "$i"
  case $i in
    "4") echo "bad luck from China";;
    "9") echo "bad luck from Japan";;
    "17") echo "bad luck from Italy";;
  esac
  (( i++ ))
done
