#!/usr/bin/env bash
# Dislays time for 12 hrs and 59 mins
# display hours from 0 to 12
#display mins from 1 to 59

hour=0

while [ $hour -le 12 ]
do
  echo "Hour: $hour"
  min=1
  while [ $min -le 59 ]
  do
    echo "$min"
    (( min++ ))
  done
  (( hour++ ))
done
