#!/usr/bin/env bash
# Displays the content of the currrent directory
# in a list format
# where only the part of the name after dash is displayed

LIST=$(ls)
for i in $LIST; do
   echo "$i" | cut -d '-' -f2
done
