#!/usr/bin/env bash
# gives information about school file
# check if file exists and print it exists
# if not then it does not exist
# if exists then ...

if [ -e "school" ]
then
  echo "school file exists"
  if [ -s "school" ]
  then
    echo "school file is not empty"
  else
    echo "school file is empty"
  fi

  if [ -f "school" ]
  then
    echo "school is a regular file"
  fi

else
  echo "school file does notb exist"
fi 
