#!/usr/bin/env bash
# configiures an ubuntu server with:
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8

cp /etc/hosts hosts_new
sed -i 's/127.0.0.1\tlocalhost/127.0.0.2 localhost\n8.8.8.8 facebook.com/' >> hosts_new
cp hosts_new /etc/hosts
